### PR TITLE
Update Meme-Analysis.ipynb

### PR DESCRIPTION
**Pull request by tylerjrichards**
added x ticks to meme graph

### CODE REVIEW

**Comment by abhisuri97** [comment]
Hey @tylerjrichards can you attach a screenshot of the new visualization? I took a look on your fork and it looks like the only addition is the seaborn plot (thanks for introducing that library, looks amazing!) but i just wanted to confirm bc github doesn't show changes to ipynb files well.

**Comment by abhisuri97** [comment]
Oh nevermind i just saw your facebook comment. looks good to me!

**Comment by tylerjrichards** [comment]
Of course! I didn't change much I just couldn't see the dates
Screen Shot 2019-05-11 at 12 39 49 PM

**Comment by tylerjrichards** [comment]
ah sweet, got it

**Pull request merged**
